[package]
name = "backend"
version = "0.1.0"

[build]
outputDir = "src/backend/dist"
args = [ "--release" ]

[canisters.backend]
main = "src/backend/main.mo"

  [canisters.backend.check-stable]
  path = ".old/src/backend/dist/backend.most"

[toolchain]
moc = "1.8.2"
lintoko = "0.10.0"

[lint]
extends = true

[moc]
args = [
  "--default-persistent-actors",
  "--actor-idl=src/backend/system-idl",
  "--implicit-package=core",
  "-no-check-ir",
  "-E=M0236,M0223,M0237,M0254",
  "-W=M0235",
  "-A=M0241"
]

[dependencies]
core = "2.5.0"
caffeineai-object-storage = "1.0.0"
caffeineai-authorization = "1.0.0"
caffeineai-user-approval = "0.1.1"
