/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const IdPassGroupLink = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'groupNumber' : IDL.Nat,
  'createdAt' : Time,
  'groupId' : IDL.Nat,
  'groupLink' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'playerId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const CaptainInfo = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const TeamRegistration = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Opt(IDL.Principal),
  'teamName' : IDL.Text,
  'members' : IDL.Vec(TeamMember),
  'groupNumber' : IDL.Nat,
  'logo' : ExternalBlob,
  'idPassAssigned' : IDL.Bool,
  'captain' : CaptainInfo,
  'teamId' : IDL.Nat,
  'groupLink' : IDL.Opt(IDL.Text),
});
export const ReportMetadata = IDL.Record({
  'created' : Time,
  'blob' : ExternalBlob,
  'size' : IDL.Nat,
  'filename' : IDL.Text,
});
export const Result = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const LogoUpload = IDL.Record({
  'teamName' : IDL.Text,
  'logo' : ExternalBlob,
  'fileSize' : IDL.Nat,
  'uploadTime' : Time,
});
export const Banner = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'image' : ExternalBlob,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DuplicateReason = IDL.Variant({
  'captainPhone' : IDL.Null,
  'teamName' : IDL.Null,
});
export const DuplicateEntry = IDL.Record({
  'originalId' : IDL.Text,
  'duplicatedAt' : Time,
  'duplicateId' : IDL.Text,
  'reason' : DuplicateReason,
});
export const RegistrationSummary = IDL.Record({
  'totalTeams' : IDL.Nat,
  'confirmedTeams' : IDL.Nat,
  'maxTeams' : IDL.Opt(IDL.Nat),
});
export const SocialMediaLinks = IDL.Record({
  'instagram' : IDL.Opt(IDL.Text),
  'whatsapp' : IDL.Opt(IDL.Text),
  'discord' : IDL.Opt(IDL.Text),
  'youtube' : IDL.Opt(IDL.Text),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addGroupLink' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdateIdPassStatus' : IDL.Func([IDL.Bool], [], []),
  'checkTeamLogoExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'closeRegistration' : IDL.Func([IDL.Bool], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'createGroupLink' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'createResult' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
  'deleteBanner' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteDuplicateEntry' : IDL.Func([IDL.Text], [], []),
  'deleteGroupLink' : IDL.Func([IDL.Nat], [], []),
  'deleteRegistration' : IDL.Func([IDL.Text], [], []),
  'deleteReport' : IDL.Func([IDL.Text], [], []),
  'deleteResult' : IDL.Func([IDL.Text], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllGroupLinks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getAllGroupLinksWithInfo' : IDL.Func(
      [],
      [IDL.Vec(IdPassGroupLink)],
      ['query'],
    ),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(TeamRegistration)], ['query']),
  'getAllReports' : IDL.Func([], [IDL.Vec(ReportMetadata)], ['query']),
  'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'getAllTeamLogosPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(LogoUpload)],
      ['query'],
    ),
  'getAllTeamsWithGroupInfo' : IDL.Func(
      [],
      [IDL.Vec(TeamRegistration)],
      ['query'],
    ),
  'getAllTeamsWithIdPassStatus' : IDL.Func(
      [],
      [IDL.Vec(TeamRegistration)],
      ['query'],
    ),
  'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
  'getAnnouncementsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getBanner' : IDL.Func([], [IDL.Opt(Banner)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDuplicateRegistrations' : IDL.Func(
      [],
      [IDL.Vec(DuplicateEntry)],
      ['query'],
    ),
  'getGroupLink' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getGroupLinkById' : IDL.Func([IDL.Nat], [IdPassGroupLink], ['query']),
  'getIdPassStatus' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'getLogoByTeamName' : IDL.Func([IDL.Text], [LogoUpload], ['query']),
  'getMaxTeamRegistrations' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getRegistrationStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getRegistrationSummary' : IDL.Func([], [RegistrationSummary], ['query']),
  'getReport' : IDL.Func([IDL.Text], [ReportMetadata], ['query']),
  'getResult' : IDL.Func([IDL.Text], [Result], ['query']),
  'getResultsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSocialMediaLinks' : IDL.Func([], [SocialMediaLinks], ['query']),
  'getTeamById' : IDL.Func([IDL.Nat], [TeamRegistration], ['query']),
  'getTeamDetailsViewer' : IDL.Func([], [IDL.Vec(TeamRegistration)], ['query']),
  'getTeamRegistration' : IDL.Func([IDL.Text], [TeamRegistration], ['query']),
  'getTeamsByIdPassStatus' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(TeamRegistration)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchGroupLinkByTeam' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IdPassGroupLink)],
      ['query'],
    ),
  'searchGroupLinks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IdPassGroupLink)],
      ['query'],
    ),
  'searchTeamsByIdPassStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TeamRegistration)],
      ['query'],
    ),
  'searchTeamsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TeamRegistration)],
      ['query'],
    ),
  'searchTeamsByNameOrPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TeamRegistration)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setBanner' : IDL.Func(
      [ExternalBlob],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setMaxTeamRegistrations' : IDL.Func([IDL.Opt(IDL.Nat)], [], []),
  'storeReport' : IDL.Func([IDL.Text, ExternalBlob, IDL.Nat], [], []),
  'submitRegistration' : IDL.Func(
      [IDL.Text, ExternalBlob, CaptainInfo, IDL.Vec(TeamMember)],
      [IDL.Text],
      [],
    ),
  'updateAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateGroupLink' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateIdPassStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateLogo' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'updateResult' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateSocialMediaLinks' : IDL.Func([SocialMediaLinks], [], []),
  'uploadTeamLogo' : IDL.Func([IDL.Text, ExternalBlob, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const IdPassGroupLink = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'groupNumber' : IDL.Nat,
    'createdAt' : Time,
    'groupId' : IDL.Nat,
    'groupLink' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'playerId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const CaptainInfo = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const TeamRegistration = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Opt(IDL.Principal),
    'teamName' : IDL.Text,
    'members' : IDL.Vec(TeamMember),
    'groupNumber' : IDL.Nat,
    'logo' : ExternalBlob,
    'idPassAssigned' : IDL.Bool,
    'captain' : CaptainInfo,
    'teamId' : IDL.Nat,
    'groupLink' : IDL.Opt(IDL.Text),
  });
  const ReportMetadata = IDL.Record({
    'created' : Time,
    'blob' : ExternalBlob,
    'size' : IDL.Nat,
    'filename' : IDL.Text,
  });
  const Result = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const LogoUpload = IDL.Record({
    'teamName' : IDL.Text,
    'logo' : ExternalBlob,
    'fileSize' : IDL.Nat,
    'uploadTime' : Time,
  });
  const Banner = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'image' : ExternalBlob,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DuplicateReason = IDL.Variant({
    'captainPhone' : IDL.Null,
    'teamName' : IDL.Null,
  });
  const DuplicateEntry = IDL.Record({
    'originalId' : IDL.Text,
    'duplicatedAt' : Time,
    'duplicateId' : IDL.Text,
    'reason' : DuplicateReason,
  });
  const RegistrationSummary = IDL.Record({
    'totalTeams' : IDL.Nat,
    'confirmedTeams' : IDL.Nat,
    'maxTeams' : IDL.Opt(IDL.Nat),
  });
  const SocialMediaLinks = IDL.Record({
    'instagram' : IDL.Opt(IDL.Text),
    'whatsapp' : IDL.Opt(IDL.Text),
    'discord' : IDL.Opt(IDL.Text),
    'youtube' : IDL.Opt(IDL.Text),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addGroupLink' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdateIdPassStatus' : IDL.Func([IDL.Bool], [], []),
    'checkTeamLogoExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'closeRegistration' : IDL.Func([IDL.Bool], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'createGroupLink' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'createResult' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Text], [], []),
    'deleteBanner' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteDuplicateEntry' : IDL.Func([IDL.Text], [], []),
    'deleteGroupLink' : IDL.Func([IDL.Nat], [], []),
    'deleteRegistration' : IDL.Func([IDL.Text], [], []),
    'deleteReport' : IDL.Func([IDL.Text], [], []),
    'deleteResult' : IDL.Func([IDL.Text], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllGroupLinks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getAllGroupLinksWithInfo' : IDL.Func(
        [],
        [IDL.Vec(IdPassGroupLink)],
        ['query'],
      ),
    'getAllRegistrations' : IDL.Func(
        [],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'getAllReports' : IDL.Func([], [IDL.Vec(ReportMetadata)], ['query']),
    'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'getAllTeamLogosPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(LogoUpload)],
        ['query'],
      ),
    'getAllTeamsWithGroupInfo' : IDL.Func(
        [],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'getAllTeamsWithIdPassStatus' : IDL.Func(
        [],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
    'getAnnouncementsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getBanner' : IDL.Func([], [IDL.Opt(Banner)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDuplicateRegistrations' : IDL.Func(
        [],
        [IDL.Vec(DuplicateEntry)],
        ['query'],
      ),
    'getGroupLink' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getGroupLinkById' : IDL.Func([IDL.Nat], [IdPassGroupLink], ['query']),
    'getIdPassStatus' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'getLogoByTeamName' : IDL.Func([IDL.Text], [LogoUpload], ['query']),
    'getMaxTeamRegistrations' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getRegistrationStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getRegistrationSummary' : IDL.Func([], [RegistrationSummary], ['query']),
    'getReport' : IDL.Func([IDL.Text], [ReportMetadata], ['query']),
    'getResult' : IDL.Func([IDL.Text], [Result], ['query']),
    'getResultsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSocialMediaLinks' : IDL.Func([], [SocialMediaLinks], ['query']),
    'getTeamById' : IDL.Func([IDL.Nat], [TeamRegistration], ['query']),
    'getTeamDetailsViewer' : IDL.Func(
        [],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'getTeamRegistration' : IDL.Func([IDL.Text], [TeamRegistration], ['query']),
    'getTeamsByIdPassStatus' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchGroupLinkByTeam' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IdPassGroupLink)],
        ['query'],
      ),
    'searchGroupLinks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IdPassGroupLink)],
        ['query'],
      ),
    'searchTeamsByIdPassStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'searchTeamsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'searchTeamsByNameOrPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TeamRegistration)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setBanner' : IDL.Func(
        [ExternalBlob],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setMaxTeamRegistrations' : IDL.Func([IDL.Opt(IDL.Nat)], [], []),
    'storeReport' : IDL.Func([IDL.Text, ExternalBlob, IDL.Nat], [], []),
    'submitRegistration' : IDL.Func(
        [IDL.Text, ExternalBlob, CaptainInfo, IDL.Vec(TeamMember)],
        [IDL.Text],
        [],
      ),
    'updateAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateGroupLink' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateIdPassStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateLogo' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'updateResult' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSocialMediaLinks' : IDL.Func([SocialMediaLinks], [], []),
    'uploadTeamLogo' : IDL.Func([IDL.Text, ExternalBlob, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };