/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'title' : string,
  'link' : [] | [string],
  'createdAt' : Time,
  'description' : string,
  'image' : ExternalBlob,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CaptainInfo { 'name' : string, 'phone' : string }
export interface DuplicateEntry {
  'originalId' : string,
  'duplicatedAt' : Time,
  'duplicateId' : string,
  'reason' : DuplicateReason,
}
export type DuplicateReason = { 'captainPhone' : null } |
  { 'teamName' : null };
export type ExternalBlob = Uint8Array;
export interface IdPassGroupLink {
  'id' : string,
  'creator' : Principal,
  'groupNumber' : bigint,
  'createdAt' : Time,
  'groupId' : bigint,
  'groupLink' : string,
}
export interface LogoUpload {
  'teamName' : string,
  'logo' : ExternalBlob,
  'fileSize' : bigint,
  'uploadTime' : Time,
}
export interface RegistrationSummary {
  'totalTeams' : bigint,
  'confirmedTeams' : bigint,
  'maxTeams' : [] | [bigint],
}
export interface ReportMetadata {
  'created' : Time,
  'blob' : ExternalBlob,
  'size' : bigint,
  'filename' : string,
}
export interface Result {
  'id' : string,
  'title' : string,
  'link' : [] | [string],
  'createdAt' : Time,
  'description' : string,
  'image' : ExternalBlob,
}
export interface SocialMediaLinks {
  'instagram' : [] | [string],
  'whatsapp' : [] | [string],
  'discord' : [] | [string],
  'youtube' : [] | [string],
}
export interface TeamMember { 'playerId' : [] | [string], 'name' : string }
export interface TeamRegistration {
  'id' : string,
  'creator' : [] | [Principal],
  'teamName' : string,
  'members' : Array<TeamMember>,
  'groupNumber' : bigint,
  'logo' : ExternalBlob,
  'idPassAssigned' : boolean,
  'captain' : CaptainInfo,
  'teamId' : bigint,
  'groupLink' : [] | [string],
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addGroupLink' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateIdPassStatus' : ActorMethod<[boolean], undefined>,
  'checkTeamLogoExists' : ActorMethod<[string], boolean>,
  'closeRegistration' : ActorMethod<[boolean], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, ExternalBlob, [] | [string]],
    string
  >,
  'createGroupLink' : ActorMethod<[bigint, bigint, string], undefined>,
  'createResult' : ActorMethod<
    [string, ExternalBlob, string, [] | [string]],
    string
  >,
  'deleteAnnouncement' : ActorMethod<[string], undefined>,
  'deleteDuplicateEntry' : ActorMethod<[string], undefined>,
  'deleteGroupLink' : ActorMethod<[bigint], undefined>,
  'deleteRegistration' : ActorMethod<[string], undefined>,
  'deleteReport' : ActorMethod<[string], undefined>,
  'deleteResult' : ActorMethod<[string], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllGroupLinks' : ActorMethod<[], Array<[bigint, string]>>,
  'getAllGroupLinksWithInfo' : ActorMethod<[], Array<IdPassGroupLink>>,
  'getAllRegistrations' : ActorMethod<[], Array<TeamRegistration>>,
  'getAllReports' : ActorMethod<[], Array<ReportMetadata>>,
  'getAllResults' : ActorMethod<[], Array<Result>>,
  'getAllTeamLogosPaginated' : ActorMethod<[bigint, bigint], Array<LogoUpload>>,
  'getAllTeamsWithGroupInfo' : ActorMethod<[], Array<TeamRegistration>>,
  'getAllTeamsWithIdPassStatus' : ActorMethod<[], Array<TeamRegistration>>,
  'getAnnouncement' : ActorMethod<[string], Announcement>,
  'getAnnouncementsCount' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDuplicateRegistrations' : ActorMethod<[], Array<DuplicateEntry>>,
  'getGroupLink' : ActorMethod<[bigint], [] | [string]>,
  'getGroupLinkById' : ActorMethod<[bigint], IdPassGroupLink>,
  'getIdPassStatus' : ActorMethod<[bigint], boolean>,
  'getLogoByTeamName' : ActorMethod<[string], LogoUpload>,
  'getMaxTeamRegistrations' : ActorMethod<[], [] | [bigint]>,
  'getRegistrationStatus' : ActorMethod<[], boolean>,
  'getRegistrationSummary' : ActorMethod<[], RegistrationSummary>,
  'getReport' : ActorMethod<[string], ReportMetadata>,
  'getResult' : ActorMethod<[string], Result>,
  'getResultsCount' : ActorMethod<[], bigint>,
  'getSocialMediaLinks' : ActorMethod<[], SocialMediaLinks>,
  'getTeamById' : ActorMethod<[bigint], TeamRegistration>,
  'getTeamDetailsViewer' : ActorMethod<[], Array<TeamRegistration>>,
  'getTeamRegistration' : ActorMethod<[string], TeamRegistration>,
  'getTeamsByIdPassStatus' : ActorMethod<[boolean], Array<TeamRegistration>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchGroupLinkByTeam' : ActorMethod<
    [string, string],
    [] | [IdPassGroupLink]
  >,
  'searchGroupLinks' : ActorMethod<[string], Array<IdPassGroupLink>>,
  'searchTeamsByIdPassStatus' : ActorMethod<[string], Array<TeamRegistration>>,
  'searchTeamsByName' : ActorMethod<[string], Array<TeamRegistration>>,
  'searchTeamsByNameOrPhone' : ActorMethod<[string], Array<TeamRegistration>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setMaxTeamRegistrations' : ActorMethod<[[] | [bigint]], undefined>,
  'storeReport' : ActorMethod<[string, ExternalBlob, bigint], undefined>,
  'submitRegistration' : ActorMethod<
    [string, ExternalBlob, CaptainInfo, Array<TeamMember>],
    string
  >,
  'updateAnnouncement' : ActorMethod<
    [string, string, string, ExternalBlob, [] | [string]],
    undefined
  >,
  'updateGroupLink' : ActorMethod<[bigint, string], undefined>,
  'updateIdPassStatus' : ActorMethod<[bigint, boolean], undefined>,
  'updateLogo' : ActorMethod<[string, ExternalBlob], undefined>,
  'updateResult' : ActorMethod<
    [string, string, ExternalBlob, string, [] | [string]],
    undefined
  >,
  'updateSocialMediaLinks' : ActorMethod<[SocialMediaLinks], undefined>,
  'uploadTeamLogo' : ActorMethod<[string, ExternalBlob, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];