/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface LogoUpload {
    teamName: string;
    logo: ExternalBlob;
    fileSize: bigint;
    uploadTime: Time;
}
export interface SocialMediaLinks {
    instagram?: string;
    whatsapp?: string;
    discord?: string;
    youtube?: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ReportMetadata {
    created: Time;
    blob: ExternalBlob;
    size: bigint;
    filename: string;
}
export interface TeamRegistration {
    id: string;
    creator?: Principal;
    teamName: string;
    members: Array<TeamMember>;
    groupNumber: bigint;
    logo: ExternalBlob;
    idPassAssigned: boolean;
    captain: CaptainInfo;
    teamId: bigint;
    groupLink?: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface DuplicateEntry {
    originalId: string;
    duplicatedAt: Time;
    duplicateId: string;
    reason: DuplicateReason;
}
export interface Result {
    id: string;
    title: string;
    link?: string;
    createdAt: Time;
    description: string;
    image: ExternalBlob;
}
export interface CaptainInfo {
    name: string;
    phone: string;
}
export interface Banner {
    id: string;
    createdAt: bigint;
    image: ExternalBlob;
}
export interface RegistrationSummary {
    totalTeams: bigint;
    confirmedTeams: bigint;
    maxTeams?: bigint;
}
export interface TeamMember {
    playerId?: string;
    name: string;
}
export interface IdPassGroupLink {
    id: string;
    creator: Principal;
    groupNumber: bigint;
    createdAt: Time;
    groupId: bigint;
    groupLink: string;
}
export interface Announcement {
    id: string;
    title: string;
    link?: string;
    createdAt: Time;
    description: string;
    image: ExternalBlob;
}
export interface UserProfile {
    name: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum DuplicateReason {
    captainPhone = "captainPhone",
    teamName = "teamName"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addGroupLink(groupNumber: bigint, link: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkUpdateIdPassStatus(status: boolean): Promise<void>;
    checkTeamLogoExists(teamName: string): Promise<boolean>;
    closeRegistration(status: boolean): Promise<void>;
    createAnnouncement(title: string, description: string, image: ExternalBlob, link: string | null): Promise<string>;
    createGroupLink(groupId: bigint, groupNumber: bigint, groupLink: string): Promise<void>;
    createResult(title: string, image: ExternalBlob, description: string, link: string | null): Promise<string>;
    deleteAnnouncement(id: string): Promise<void>;
    deleteBanner(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteDuplicateEntry(id: string): Promise<void>;
    deleteGroupLink(groupId: bigint): Promise<void>;
    deleteRegistration(id: string): Promise<void>;
    deleteReport(filename: string): Promise<void>;
    deleteResult(id: string): Promise<void>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllGroupLinks(): Promise<Array<[bigint, string]>>;
    getAllGroupLinksWithInfo(): Promise<Array<IdPassGroupLink>>;
    getAllRegistrations(): Promise<Array<TeamRegistration>>;
    getAllReports(): Promise<Array<ReportMetadata>>;
    getAllResults(): Promise<Array<Result>>;
    getAllTeamLogosPaginated(pageNumber: bigint, pageSize: bigint): Promise<Array<LogoUpload>>;
    getAllTeamsWithGroupInfo(): Promise<Array<TeamRegistration>>;
    getAllTeamsWithIdPassStatus(): Promise<Array<TeamRegistration>>;
    getAnnouncement(id: string): Promise<Announcement>;
    getAnnouncementsCount(): Promise<bigint>;
    getBanner(): Promise<Banner | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDuplicateRegistrations(): Promise<Array<DuplicateEntry>>;
    getGroupLink(groupNumber: bigint): Promise<string | null>;
    getGroupLinkById(groupId: bigint): Promise<IdPassGroupLink>;
    getIdPassStatus(teamId: bigint): Promise<boolean>;
    getLogoByTeamName(teamName: string): Promise<LogoUpload>;
    getMaxTeamRegistrations(): Promise<bigint | null>;
    getRegistrationStatus(): Promise<boolean>;
    getRegistrationSummary(): Promise<RegistrationSummary>;
    getReport(filename: string): Promise<ReportMetadata>;
    getResult(id: string): Promise<Result>;
    getResultsCount(): Promise<bigint>;
    getSocialMediaLinks(): Promise<SocialMediaLinks>;
    getTeamById(teamId: bigint): Promise<TeamRegistration>;
    getTeamDetailsViewer(): Promise<Array<TeamRegistration>>;
    getTeamRegistration(id: string): Promise<TeamRegistration>;
    getTeamsByIdPassStatus(status: boolean): Promise<Array<TeamRegistration>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchGroupLinkByTeam(teamName: string, phoneNumber: string): Promise<IdPassGroupLink | null>;
    searchGroupLinks(searchTerm: string): Promise<Array<IdPassGroupLink>>;
    searchTeamsByIdPassStatus(searchTerm: string): Promise<Array<TeamRegistration>>;
    searchTeamsByName(searchTerm: string): Promise<Array<TeamRegistration>>;
    searchTeamsByNameOrPhone(searchTerm: string): Promise<Array<TeamRegistration>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setBanner(image: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setMaxTeamRegistrations(limit: bigint | null): Promise<void>;
    storeReport(filename: string, blob: ExternalBlob, size: bigint): Promise<void>;
    submitRegistration(teamName: string, logo: ExternalBlob, captain: CaptainInfo, members: Array<TeamMember>): Promise<string>;
    updateAnnouncement(id: string, title: string, description: string, image: ExternalBlob, link: string | null): Promise<void>;
    updateGroupLink(groupId: bigint, newLink: string): Promise<void>;
    updateIdPassStatus(teamId: bigint, status: boolean): Promise<void>;
    updateLogo(id: string, newLogo: ExternalBlob): Promise<void>;
    updateResult(id: string, title: string, image: ExternalBlob, description: string, link: string | null): Promise<void>;
    updateSocialMediaLinks(newLinks: SocialMediaLinks): Promise<void>;
    uploadTeamLogo(teamName: string, logo: ExternalBlob, fileSize: bigint): Promise<void>;
}
import type { Announcement as _Announcement, ApprovalStatus as _ApprovalStatus, Banner as _Banner, CaptainInfo as _CaptainInfo, DuplicateEntry as _DuplicateEntry, DuplicateReason as _DuplicateReason, Error as _Error, ExternalBlob as _ExternalBlob, IdPassGroupLink as _IdPassGroupLink, LogoUpload as _LogoUpload, RegistrationSummary as _RegistrationSummary, ReportMetadata as _ReportMetadata, Result as _Result, Result__1 as _Result__1, SocialMediaLinks as _SocialMediaLinks, TeamMember as _TeamMember, TeamRegistration as _TeamRegistration, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addGroupLink(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupLink(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUpdateIdPassStatus(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateIdPassStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateIdPassStatus(arg0);
            return result;
        }
    }
    async checkTeamLogoExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkTeamLogoExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkTeamLogoExists(arg0);
            return result;
        }
    }
    async closeRegistration(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeRegistration(arg0);
            return result;
        }
    }
    async createAnnouncement(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createGroupLink(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroupLink(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroupLink(arg0, arg1, arg2);
            return result;
        }
    }
    async createResult(arg0: string, arg1: ExternalBlob, arg2: string, arg3: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createResult(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResult(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteAnnouncement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteBanner(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBanner();
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBanner();
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDuplicateEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDuplicateEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDuplicateEntry(arg0);
            return result;
        }
    }
    async deleteGroupLink(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroupLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroupLink(arg0);
            return result;
        }
    }
    async deleteRegistration(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRegistration(arg0);
            return result;
        }
    }
    async deleteReport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async deleteResult(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResult(arg0);
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGroupLinks(): Promise<Array<[bigint, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGroupLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGroupLinks();
            return result;
        }
    }
    async getAllGroupLinksWithInfo(): Promise<Array<IdPassGroupLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGroupLinksWithInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGroupLinksWithInfo();
            return result;
        }
    }
    async getAllRegistrations(): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegistrations();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegistrations();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReports(): Promise<Array<ReportMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllResults(): Promise<Array<Result>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResults();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResults();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeamLogosPaginated(arg0: bigint, arg1: bigint): Promise<Array<LogoUpload>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamLogosPaginated(arg0, arg1);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamLogosPaginated(arg0, arg1);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeamsWithGroupInfo(): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamsWithGroupInfo();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamsWithGroupInfo();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeamsWithIdPassStatus(): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamsWithIdPassStatus();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamsWithIdPassStatus();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnnouncement(arg0: string): Promise<Announcement> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncement(arg0);
                return from_candid_Announcement_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncement(arg0);
            return from_candid_Announcement_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnnouncementsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncementsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncementsCount();
            return result;
        }
    }
    async getBanner(): Promise<Banner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBanner();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBanner();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDuplicateRegistrations(): Promise<Array<DuplicateEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDuplicateRegistrations();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDuplicateRegistrations();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupLink(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupLink(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupLink(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupLinkById(arg0: bigint): Promise<IdPassGroupLink> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupLinkById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupLinkById(arg0);
            return result;
        }
    }
    async getIdPassStatus(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdPassStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdPassStatus(arg0);
            return result;
        }
    }
    async getLogoByTeamName(arg0: string): Promise<LogoUpload> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogoByTeamName(arg0);
                return from_candid_LogoUpload_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogoByTeamName(arg0);
            return from_candid_LogoUpload_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaxTeamRegistrations(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaxTeamRegistrations();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaxTeamRegistrations();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistrationStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationStatus();
            return result;
        }
    }
    async getRegistrationSummary(): Promise<RegistrationSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationSummary();
                return from_candid_RegistrationSummary_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationSummary();
            return from_candid_RegistrationSummary_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: string): Promise<ReportMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_ReportMetadata_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_ReportMetadata_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResult(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.getResult(arg0);
                return from_candid_Result_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResult(arg0);
            return from_candid_Result_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResultsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getResultsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResultsCount();
            return result;
        }
    }
    async getSocialMediaLinks(): Promise<SocialMediaLinks> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialMediaLinks();
                return from_candid_SocialMediaLinks_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialMediaLinks();
            return from_candid_SocialMediaLinks_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamById(arg0: bigint): Promise<TeamRegistration> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamById(arg0);
                return from_candid_TeamRegistration_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamById(arg0);
            return from_candid_TeamRegistration_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamDetailsViewer(): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamDetailsViewer();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamDetailsViewer();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamRegistration(arg0: string): Promise<TeamRegistration> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamRegistration(arg0);
                return from_candid_TeamRegistration_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamRegistration(arg0);
            return from_candid_TeamRegistration_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamsByIdPassStatus(arg0: boolean): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamsByIdPassStatus(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamsByIdPassStatus(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchGroupLinkByTeam(arg0: string, arg1: string): Promise<IdPassGroupLink | null> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGroupLinkByTeam(arg0, arg1);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGroupLinkByTeam(arg0, arg1);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchGroupLinks(arg0: string): Promise<Array<IdPassGroupLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGroupLinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGroupLinks(arg0);
            return result;
        }
    }
    async searchTeamsByIdPassStatus(arg0: string): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTeamsByIdPassStatus(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTeamsByIdPassStatus(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchTeamsByName(arg0: string): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTeamsByName(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTeamsByName(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchTeamsByNameOrPhone(arg0: string): Promise<Array<TeamRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTeamsByNameOrPhone(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTeamsByNameOrPhone(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setBanner(arg0: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setBanner(await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBanner(await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async setMaxTeamRegistrations(arg0: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMaxTeamRegistrations(to_candid_opt_n60(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMaxTeamRegistrations(to_candid_opt_n60(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async storeReport(arg0: string, arg1: ExternalBlob, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeReport(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeReport(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async submitRegistration(arg0: string, arg1: ExternalBlob, arg2: CaptainInfo, arg3: Array<TeamMember>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRegistration(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_vec_n61(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRegistration(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_vec_n61(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateAnnouncement(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, arg1, arg2, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateGroupLink(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGroupLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGroupLink(arg0, arg1);
            return result;
        }
    }
    async updateIdPassStatus(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIdPassStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIdPassStatus(arg0, arg1);
            return result;
        }
    }
    async updateLogo(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLogo(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLogo(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateResult(arg0: string, arg1: string, arg2: ExternalBlob, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResult(arg0, arg1, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResult(arg0, arg1, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateSocialMediaLinks(arg0: SocialMediaLinks): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSocialMediaLinks(to_candid_SocialMediaLinks_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSocialMediaLinks(to_candid_SocialMediaLinks_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadTeamLogo(arg0: string, arg1: ExternalBlob, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadTeamLogo(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadTeamLogo(arg0, await to_candid_ExternalBlob_n14(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
}
async function from_candid_Announcement_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Promise<Announcement> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
async function from_candid_Banner_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Banner): Promise<Banner> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_DuplicateEntry_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DuplicateEntry): DuplicateEntry {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_DuplicateReason_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DuplicateReason): DuplicateReason {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_LogoUpload_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogoUpload): Promise<LogoUpload> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationSummary_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationSummary): RegistrationSummary {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
async function from_candid_ReportMetadata_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportMetadata): Promise<ReportMetadata> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_Result_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Promise<Result> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SocialMediaLinks_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialMediaLinks): SocialMediaLinks {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_TeamMember_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMember): TeamMember {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_TeamRegistration_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamRegistration): Promise<TeamRegistration> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Banner]): Promise<Banner | null> {
    return value.length === 0 ? null : await from_candid_Banner_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IdPassGroupLink]): IdPassGroupLink | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    link: [] | [string];
    createdAt: _Time;
    description: string;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    link?: string;
    createdAt: Time;
    description: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        link: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.link)),
        createdAt: value.createdAt,
        description: value.description,
        image: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: [] | [Principal];
    teamName: string;
    members: Array<_TeamMember>;
    groupNumber: bigint;
    logo: _ExternalBlob;
    idPassAssigned: boolean;
    captain: _CaptainInfo;
    teamId: bigint;
    groupLink: [] | [string];
}): Promise<{
    id: string;
    creator?: Principal;
    teamName: string;
    members: Array<TeamMember>;
    groupNumber: bigint;
    logo: ExternalBlob;
    idPassAssigned: boolean;
    captain: CaptainInfo;
    teamId: bigint;
    groupLink?: string;
}> {
    return {
        id: value.id,
        creator: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.creator)),
        teamName: value.teamName,
        members: from_candid_vec_n26(_uploadFile, _downloadFile, value.members),
        groupNumber: value.groupNumber,
        logo: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.logo),
        idPassAssigned: value.idPassAssigned,
        captain: value.captain,
        teamId: value.teamId,
        groupLink: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.groupLink))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerId: [] | [string];
    name: string;
}): {
    playerId?: string;
    name: string;
} {
    return {
        playerId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.playerId)),
        name: value.name
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: _Time;
    blob: _ExternalBlob;
    size: bigint;
    filename: string;
}): Promise<{
    created: Time;
    blob: ExternalBlob;
    size: bigint;
    filename: string;
}> {
    return {
        created: value.created,
        blob: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.blob),
        size: value.size,
        filename: value.filename
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamName: string;
    logo: _ExternalBlob;
    fileSize: bigint;
    uploadTime: _Time;
}): Promise<{
    teamName: string;
    logo: ExternalBlob;
    fileSize: bigint;
    uploadTime: Time;
}> {
    return {
        teamName: value.teamName,
        logo: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.logo),
        fileSize: value.fileSize,
        uploadTime: value.uploadTime
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: bigint;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    createdAt: bigint;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        createdAt: value.createdAt,
        image: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    originalId: string;
    duplicatedAt: _Time;
    duplicateId: string;
    reason: _DuplicateReason;
}): {
    originalId: string;
    duplicatedAt: Time;
    duplicateId: string;
    reason: DuplicateReason;
} {
    return {
        originalId: value.originalId,
        duplicatedAt: value.duplicatedAt,
        duplicateId: value.duplicateId,
        reason: from_candid_DuplicateReason_n46(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalTeams: bigint;
    confirmedTeams: bigint;
    maxTeams: [] | [bigint];
}): {
    totalTeams: bigint;
    confirmedTeams: bigint;
    maxTeams?: bigint;
} {
    return {
        totalTeams: value.totalTeams,
        confirmedTeams: value.confirmedTeams,
        maxTeams: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.maxTeams))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    instagram: [] | [string];
    whatsapp: [] | [string];
    discord: [] | [string];
    youtube: [] | [string];
}): {
    instagram?: string;
    whatsapp?: string;
    discord?: string;
    youtube?: string;
} {
    return {
        instagram: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.instagram)),
        whatsapp: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.whatsapp)),
        discord: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.discord)),
        youtube: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.youtube))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n55(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    captainPhone: null;
} | {
    teamName: null;
}): DuplicateReason {
    return "captainPhone" in value ? DuplicateReason.captainPhone : "teamName" in value ? DuplicateReason.teamName : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Promise<Array<Announcement>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Announcement_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamRegistration>): Promise<Array<TeamRegistration>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TeamRegistration_n23(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamMember>): Array<TeamMember> {
    return value.map((x)=>from_candid_TeamMember_n27(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReportMetadata>): Promise<Array<ReportMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ReportMetadata_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Result>): Promise<Array<Result>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Result_n33(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LogoUpload>): Promise<Array<LogoUpload>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LogoUpload_n35(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DuplicateEntry>): Array<DuplicateEntry> {
    return value.map((x)=>from_candid_DuplicateEntry_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n53(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SocialMediaLinks_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialMediaLinks): _SocialMediaLinks {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_TeamMember_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamMember): _TeamMember {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerId?: string;
    name: string;
}): {
    playerId: [] | [string];
    name: string;
} {
    return {
        playerId: value.playerId ? candid_some(value.playerId) : candid_none(),
        name: value.name
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    instagram?: string;
    whatsapp?: string;
    discord?: string;
    youtube?: string;
}): {
    instagram: [] | [string];
    whatsapp: [] | [string];
    discord: [] | [string];
    youtube: [] | [string];
} {
    return {
        instagram: value.instagram ? candid_some(value.instagram) : candid_none(),
        whatsapp: value.whatsapp ? candid_some(value.whatsapp) : candid_none(),
        discord: value.discord ? candid_some(value.discord) : candid_none(),
        youtube: value.youtube ? candid_some(value.youtube) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TeamMember>): Array<_TeamMember> {
    return value.map((x)=>to_candid_TeamMember_n62(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
